Bookstore-Mission9/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bookstore_Mission9.Models;
using Bookstore.Models;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private ShoppingCart cart;
        public CartSummaryViewComponent(ShoppingCart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Bookstore-Mission9/Components/TypesViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore_Mission9.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedCat = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Bookstore-Mission9/Views/Shared/BookDesc.cshtml
@{
}
@model Book

<div class="bg-faded p-1 card card-outline-primary m-1">
    <ul>
        <div>
            <h3 class="card-text p-1">@Model.Title</h3>
        </div>

        <ul class="card-text p-1">@Model.Author</ul>
        <ul class="card-text p-1">@Model.Publisher</ul>
        <ul class="card-text p-1">@Model.Isbn</ul>
        <ul class="card-text p-1">@Model.Classification</ul>
        <ul class="card-text p-1">@Model.Category</ul>
        <ul class="card-text p-1">@Model.PageCount</ul>
        <center><ul class="badge badge-pill badge-primary" style="float:right">@Model.Price</ul></center>
    </ul>
    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Add To Cart</button>
        </span>
    </form>
</div>

Bookstore-Mission9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore_Mission9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto"></ul>

                </div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row mt-3">
            <nav class="col-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <vc:types>

                    </vc:types>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">@ViewData["Title"]</h1>
                </div>
                <div class="container">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">&copy; 2023 - Bookstore_Mission9 - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a></span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>