Bookstore-Mission9/Components/TypesViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore_Mission9.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedCat = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Bookstore-Mission9/Controllers/CartController.cs
using Bookstore_Mission9.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore_Mission9.Controllers
{
    public class CartController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private ShoppingCart cart { get; set; }
        public CartController (IPurchaseRepository temp, ShoppingCart sc)
        {
            repo = temp;
            cart = sc;
        }
        
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty.  Please add items before checking out!");
            }
            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/Complete");
            }
            else
            {
                return View();
            }
        }
    }
}

Bookstore-Mission9/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Models;
using Bookstore_Mission9.Models;
using Bookstore_Mission9.Models.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore_Mission9.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public ShoppingCart shopcart { get; set; }
        public string ReturnUrl { get; set; }

        public CartModel (IBookstoreRepository temp, ShoppingCart s)
        {
            repo = temp;
            shopcart = s;
        }
        public void OnGet(string returnurl)
        {
            ReturnUrl = returnurl ?? "/";
        }

        public IActionResult OnPost(int BookId, string returnurl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == BookId);
            shopcart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnurl });
        }

        public IActionResult OnPostRemove (int bookid, string returnUrl)
        {
            shopcart.RemoveItem(shopcart.Items.First(x => x.Book.BookId == bookid).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Bookstore-Mission9/Pages/Complete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bookstore_Mission9.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bookstore-Mission9/Pages/Cart.cshtml
@page
@model Bookstore_Mission9.Pages.CartModel
@{
}

<div class="container mt-5">
    <h1 class="text-center mb-5">Your Shopping Cart</h1>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Book Title</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model.shopcart.Items)
                    {
                        <tr>
                            <td>@i.Book.Title</td>
                            <td>@i.Quantity</td>
                            <td>@i.Book.Price.ToString("c")</td>
                            <td>@(((double)i.Book.Price *  i.Quantity).ToString("c"))</td>
                            <td>
                                <form method="post" asp-page-handler="Remove">
                                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="font-weight-bold text-right">Total</td>
                        <td class="font-weight-bold">@Model.shopcart.CalculateTotal().ToString("c")</td>
                    </tr>
                </tfoot>
            </table>
            <div class="text-center">
                <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
                <a class="btn btn-primary" asp-action="Checkout" asp-controller="Cart">Checkout</a>
            </div>
        </div>
    </div>
</div>

Bookstore-Mission9/Pages/Complete.cshtml
@page
@model Bookstore_Mission9.Pages.CompleteModel
@{
}

<div class="text-center">
    <h2>Thank you for your order! We will send you a confirmation when it has shipped.</h2>
    <a class="btn btn-primary" asp-controller="Home">Go Back To Home</a>
</div>

Bookstore-Mission9/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore_Mission9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*This is used to set the bootstrap across all the navbars for the website.*@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container bg-dark text-white p-2">
                <a class="navbar-brand ml-2" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types>

            </vc:types>
        </div>
    </div>
    <div class="container">
        <main role="main" class="col-9">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-white">
        <div class="container">
            &copy; 2023 - Bookstore_Mission9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>